const ChatActionTypes = Object.freeze({
  FETCH_MESSAGES_START: "FETCH_MESSAGES_START",
  FETCH_MESSAGES_SUCCESS: "FETCH_MESSAGES_SUCCESS",
  FETCH_MESSAGES_FAILURE: "FETCH_MESSAGES_FAILURE",
});

export default ChatActionTypes;
